"""add group specialists and services tables

Revision ID: 4599b7ebecb5
Revises: cfb2f33171d2
Create Date: 2024-11-24 13:47:24.037613

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4599b7ebecb5'
down_revision: Union[str, None] = 'cfb2f33171d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groupservices_name'), 'groupservices', ['name'], unique=False)
    op.create_index(op.f('ix_groupservices_price'), 'groupservices', ['price'], unique=False)
    op.create_table('groupspecialists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groupspecialists_name'), 'groupspecialists', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groupspecialists_name'), table_name='groupspecialists')
    op.drop_table('groupspecialists')
    op.drop_index(op.f('ix_groupservices_price'), table_name='groupservices')
    op.drop_index(op.f('ix_groupservices_name'), table_name='groupservices')
    op.drop_table('groupservices')
    # ### end Alembic commands ###
