"""create tables IndividualServices, Massage

Revision ID: cfb2f33171d2
Revises: 266471e48761
Create Date: 2024-11-21 14:21:39.125160

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb2f33171d2'
down_revision: Union[str, None] = '266471e48761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individualservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individualservices_name'), 'individualservices', ['name'], unique=False)
    op.create_index(op.f('ix_individualservices_price'), 'individualservices', ['price'], unique=False)
    op.create_table('massage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_massage_name'), 'massage', ['name'], unique=False)
    op.create_index(op.f('ix_massage_price'), 'massage', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_massage_price'), table_name='massage')
    op.drop_index(op.f('ix_massage_name'), table_name='massage')
    op.drop_table('massage')
    op.drop_index(op.f('ix_individualservices_price'), table_name='individualservices')
    op.drop_index(op.f('ix_individualservices_name'), table_name='individualservices')
    op.drop_table('individualservices')
    # ### end Alembic commands ###
